spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/api2?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    password: qibosoft
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  redis:
    host: 127.0.0.1
    port: 6379

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.lfwin.pojo